#+title: Semiotics

* Media language
 Media producers encode messages and viewpoints they want to convey, audiences decode and interpret these meanings.
* Semiotics
- Semiotics is the study of signs and meaning.
- Explores how people derive meaning from the world around them.
- A sign is anything that symbolises or represents something else.
  (e.g a buzzing sound may mean there is a bee nearby)
An example of a sign is a rose, which has connotations to love and romance.
** Categories of sign
- Icon
  Directly resembles the object, shares tangible qualities.
  (e.g a picture of a banana is an icon for it, or clapping some coconuts together is an icon for the sound of horses hooves)
- Index
  Has an implied association, they're connected in a logical way.
  (e.g the smell of smoke indicates a fire)
- Symbol
  Not inherently connected, but is a matter of convention within a culture. Symbols have to be taught and so are more likely to be misunderstood.
  (e.g dotted lines on a road, the pound sign, most words)
** Barthes
 Barthes argues that constructed meanings (symbols) can come to seem self evident, achieving the status of myth through a process of naturalisation.

 These connotations are often limited to culture, for example in western cultures red is associated with love or danger. But in eastern cultures it's associated with luck, long life, and happiness.

 This means that if red was used in a peice of media, for example a website showing an error in red, it'd be read differently by people from different cultures.
